### ISSUE TITLE
Revert cats-effect update to 3.6.2

### ISSUE THREAD

**Issue by dpevunov-cp** [typelevel/doobie#2291]
Revert cats-effect update to 3.6.2 due to the critical bug found in cats -> https://github.com/typelevel/cats-effect/issues/4448

**Comment by mzuehlke** [comment]
That got fixed in cats-effect 3.6.3.

The update to that was:
* #2289

**Comment by dpevunov-cp** [comment]
I know but still having this lib available with broken cats-effect leaves the danger of using bugged version of cats-effect. Could you release newer version and somehow mark RC10 as bugged?
